version: '3.7'

services:
  video-downloader-gui:
    build: .
    container_name: 'video-downloader-gui'
    restart: 'always'
    environment:
      - VIRTUAL_HOST=videodownloader.alpi314.com
      - LETSENCRYPT_HOST=videodownloader.alpi314.com
      - VIRTUAL_PORT=5000
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - net
      - postgres-network
    privileged: true

networks:
  net:
    external: true
  postgres-network:
    external: true
